# Generated by Django 6.0.7 on 2026-07-15 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_user_id_4e08b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_status_762191_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_created_77e2b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_order_i_26ad88_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='order_items_product_a53db1_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_user_id_535113_idx'),
        ),
    ]
