# Generated by Django 6.0.7 on 2026-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cleanup_duplicate_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
