# Generated by Django 6.0.7 on 2026-07-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='accounts_us_email_74c8d6_idx',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
