# Generated by Django 6.0.7 on 2026-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], db_index=True, default='customer', max_length=20),
        ),
    ]
