# Generated by Django 6.0.7 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
