# Generated by Django 6.0.7 on 2026-07-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cleanup_duplicate_indexes'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'date_joined'], name='users_user_ty_3b3d70_idx'),
        ),
    ]
