export const products = [
  {
    id: 1,
    name: 'Wireless Headphones',
    sku: 'WH-100',
    description: 'Over-ear headphones with noise cancelling',
    price: 89.99,
    stock: 24,
    status: 'active',
  },
  {
    id: 2,
    name: 'USB-C Hub',
    sku: 'HUB-01',
    description: 'HDMI, USB 3.0, SD card reader',
    price: 39.5,
    stock: 50,
    status: 'active',
  },
  {
    id: 3,
    name: 'Mechanical Keyboard',
    sku: 'KB-75',
    description: '75% layout with RGB',
    price: 119.0,
    stock: 12,
    status: 'active',
  },
  {
    id: 4,
    name: 'Desk Lamp',
    sku: 'LAMP-2',
    description: 'LED lamp adjustable brightness',
    price: 45.0,
    stock: 0,
    status: 'active',
  },
  {
    id: 5,
    name: 'Laptop Stand',
    sku: 'ST-17',
    description: 'Aluminum stand up to 17 inch',
    price: 54.99,
    stock: 33,
    status: 'active',
  },
  {
    id: 6,
    name: 'Webcam HD',
    sku: 'CAM-HD',
    description: '1080p webcam with mic',
    price: 69.0,
    stock: 18,
    status: 'active',
  },
  {
    id: 7,
    name: 'Bluetooth Speaker',
    sku: 'SPK-BT',
    description: 'Portable waterproof speaker',
    price: 49.99,
    stock: 40,
    status: 'active',
  },
  {
    id: 8,
    name: 'Wireless Mouse',
    sku: 'MS-WL',
    description: 'Ergonomic silent-click mouse',
    price: 29.99,
    stock: 60,
    status: 'active',
  },
  {
    id: 9,
    name: 'Monitor Arm',
    sku: 'ARM-M1',
    description: 'Gas-spring single monitor mount',
    price: 79.0,
    stock: 15,
    status: 'active',
  },
  {
    id: 10,
    name: 'USB-C Cable Pack',
    sku: 'CBL-3',
    description: '3-pack braided 2m cables',
    price: 19.99,
    stock: 100,
    status: 'active',
  },
  {
    id: 11,
    name: 'Noise Cancelling Earbuds',
    sku: 'EB-NC',
    description: 'True wireless with charging case',
    price: 99.0,
    stock: 22,
    status: 'active',
  },
  {
    id: 12,
    name: 'Portable SSD 1TB',
    sku: 'SSD-1T',
    description: 'USB 3.2 external solid state drive',
    price: 109.0,
    stock: 27,
    status: 'active',
  },
  {
    id: 13,
    name: 'HDMI Cable 2m',
    sku: 'HDMI-2',
    description: '4K60 certified HDMI cable',
    price: 14.5,
    stock: 80,
    status: 'active',
  },
  {
    id: 14,
    name: 'Desk Mat XL',
    sku: 'MAT-XL',
    description: 'Extended non-slip desk pad',
    price: 24.0,
    stock: 45,
    status: 'active',
  },
  {
    id: 15,
    name: 'Phone Stand',
    sku: 'PS-01',
    description: 'Adjustable aluminum phone holder',
    price: 16.99,
    stock: 55,
    status: 'active',
  },
]

export const sampleOrders = [
  {
    id: 101,
    total_amount: 129.49,
    status: 'paid',
    created_at: '2026-07-10 14:22',
    items: [
      { product_id: 1, name: 'Wireless Headphones', quantity: 1, price: 89.99, subtotal: 89.99 },
      { product_id: 2, name: 'USB-C Hub', quantity: 1, price: 39.5, subtotal: 39.5 },
    ],
  },
  {
    id: 102,
    total_amount: 119.0,
    status: 'pending',
    created_at: '2026-07-12 09:05',
    items: [
      { product_id: 3, name: 'Mechanical Keyboard', quantity: 1, price: 119.0, subtotal: 119.0 },
    ],
  },
  {
    id: 103,
    total_amount: 69.0,
    status: 'canceled',
    created_at: '2026-07-08 18:40',
    items: [
      { product_id: 6, name: 'Webcam HD', quantity: 1, price: 69.0, subtotal: 69.0 },
    ],
  },
]

export const samplePayments = [
  {
    id: 1,
    order_id: 101,
    provider: 'stripe',
    transaction_id: 'pi_3MxTestAbc123',
    status: 'success',
    created_at: '2026-07-10 14:25',
  },
  {
    id: 2,
    order_id: 102,
    provider: 'bkash',
    transaction_id: 'TRX987654321',
    status: 'pending',
    created_at: '2026-07-12 09:06',
  },
  {
    id: 3,
    order_id: 103,
    provider: 'stripe',
    transaction_id: 'pi_3MxFailXyz789',
    status: 'failed',
    created_at: '2026-07-08 18:41',
  },
]
