# Generated by Django 6.0.7 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_order_i_b32b33_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_provide_b98dc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_status_d621e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_transac_a1f824_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
