# Generated by Django 6.0.7 on 2026-07-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_parent__7983b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_name_98d7d5_idx',
        ),
    ]
