# Generated by Django 6.0.7 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_extra_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_sku_fe2039_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_status_a30e64_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_4083ff_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
